export const AuthActionTypes = {

    USER_LOGIN_START:'USER_LOGIN_START',
    SET_USER_ROLES:'SET_USER_ROLES',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE:'USER_LOGIN_FAILURE',
    USER_LOGOUT: 'USER_LOGOUT',

    USER_REGISTRATION_START: 'USER_REGISTRATION_START',
    USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION_FAILURE: 'USER_REGISTRATION_FAILURE', 

    USER_BASIC_INFORMATION_START: 'USER_BASIC_INFORMATION_START',
    USER_BASIC_INFORMATION_SUCCESS: 'USER_BASIC_INFORMATION_SUCCESS',
    USER_BASIC_INFORMATION_FAILURE: 'USER_BASIC_INFORMATION_FAILURE', 

    REFRESH_ACCESS_TOKEN_START: 'REFRESH_ACCESS_TOKEN_START',
    REFRESH_ACCESS_TOKEN_SUCCESS: 'REFRESH_ACCESS_TOKEN_SUCCESS',
    REFRESH_ACCESS_TOKEN_FAIL: 'REFRESH_ACCESS_TOKEN_FAIL',

    USER_ACTIVATION_SUBMIT_START: 'USER_ACTIVATION_SUBMIT_START',
    USER_ACTIVATION_SUBMIT_SUCCESS: 'USER_ACTIVATION_SUBMIT_SUCCESS',
    USER_ACTIVATION_SUBMIT_FAIL: 'USER_ACTIVATION_SUBMIT_FAIL',

    USER_CHECK_EXISTS_START: 'USER_CHECK_EXISTS_START',
    USER_CHECK_EXISTS_SUCCESS: 'USER_CHECK_EXISTS_SUCCESS',
    USER_CHECK_EXISTS_FAIL: 'USER_CHECK_EXISTS_FAIL',

    USER_CREATE_PASSWORD_START: 'USER_CREATE_PASSWORD_START',
    USER_CREATE_PASSWORD_SUCCESS: 'USER_CREATE_PASSWORD_SUCCESS',
    USER_CREATE_PASSWORD_FAIL: 'USER_CREATE_PASSWORD_FAIL',

    USER_CHANGE_PASSWORD_START: 'USER_CHANGE_PASSWORD_START',
    USER_CHANGE_PASSWORD_SUCCESS: 'USER_CHANGE_PASSWORD_SUCCESS',
    USER_CHANGE_PASSWORD_FAIL: 'USER_CHANGE_PASSWORD_FAIL',

    SET_USER_NAME: 'SET_USER_NAMe',
    SET_AUTH_ERROR: 'SET_AUTH_ERROR',
    SET_USER_ID:'SET_USER_ID',

};